AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: vk-aws-test-app

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs10.x
    MemorySize: 128
    Timeout: 3

Resources:
  dynDBRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: 'Allows Lambda functions to call dynamodb'
      MaxSessionDuration: 3600
      Path: "/"
      RoleName: dynDBRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
